CMAKE_VERSION = "3.12"
CMAKE_FILE_NAME = "CMakeLists.txt"
JSON_FILE_NAME = "cmake_data.json"

DEFAULT_C_STANDARD = "99"
DEFAULT_CPP_STANDARD = "11"

EXTERNAL_GIT_REPO_DIR = "external"
EXTERNAL_BUILD_REPO_DIR = "_builds"